name: amap_base_location
description: Fully Functional AMap Flutter Plugin. Based on AndroidView/UiKitView.
version: 0.4.0+1
author: yohom <382146139@qq.com>
homepage: https://github.com/yohom/amap_base_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  amap_base_core: ^0.0.5+1
  amap_base_core:
    git:
      url: git@github.com:vrsct/amap_base_flutter.git
      path: core

flutter:
  plugin:
    androidPackage: me.yohom.amapbaselocation
    pluginClass: AMapBaseLocationPlugin

  assets:
    - images/
